[package]
name = "sslab-execution-chase"
version = "0.1.0"
authors = ["Donghyeon Ryu <donghyeonryu@postech.ac.kr>"]
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
async-trait.workspace = true
itertools.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
sui-types.workspace = true
narwhal-types.workspace = true
sslab-execution.workspace = true
evm.workspace = true
num_cpus.workspace = true
parking_lot.workspace = true

ethers-core = { version = "^2.0.0" }
rayon = "1.8.0"
nohash-hasher = "0.2.0"
hashbrown = { version = "0.14.2", features = ["inline-more", "default"] }
incr_stats = { version = "1.0.2", optional = true }
lru.workspace = true

[dev-dependencies]
ethers = "^2.0.0"
ethers-signers = { version = "^2.0.0" }
ethers-providers = { version = "^2.0.0" }
rand_distr = "0.4.3"
criterion = { workspace = true, features = ["async_tokio", "default"] }

[features]
parallelism-analysis = ["incr_stats"]
parallelism = ["parallelism-analysis", "disable-early-detection"]

disable-early-detection = []
last-committer-wins = []
disable-rescheduling = []
optimizations = ["disable-early-detection", "disable-rescheduling"]
vanilla-kdg = ["disable-early-detection", "disable-rescheduling", "last-committer-wins", "parallelism"]
vanilla-kdg-fcw = ["disable-early-detection", "disable-rescheduling", "parallelism"]

chase = []
seer = []

latency = []

[[bench]]
name = "chase"
harness = false
required-features = ["chase"]

[[bench]]
name = "parallelism"
harness = false
required-features = ["parallelism"]

[[bench]]
name = "optimizations"
harness = false
required-features = ["optimizations"]

[[bench]]
name = "latency"
harness = false
required-features = ["latency"]

[[bench]]
name = "vanilla"
harness = false
required-features = ["vanilla-kdg"]